language: ruby
env:
  global:
  - secure: E7yPFvBUKWMpqBcSTMQWssc89FJzOCCYGrNH65Zs5PpYZOrxZc+r6xWKly9MgRIYF+sdJCUM3hKd5AwNLuJnDkEzG3o/Ivdt9XZWOuzqatMj7RRcohLcJonpNMldoOROc4Goktc5qY3p0nTBQSk/jajyg2j0ZKnfemlhedpBprmEXph29m1vIL/M5/KK5Zi57HurSGazeELyGf9kKFrG1amj/E0gBuuJKmb22LbnJGmEj6Es6ow7WMZwOeR//GbiaoUycoWfXz9anRZpm8qV7SK9qh4EEus88cJOvcFuLoMmIe3hKQUoLGbvhkdkCUJ9E+rRGfYHHGjHWMRKOX7ZTQXxfbje0vI+razYHEm49nc7iuIFAmn3gBYAVq+hrLZwj0Vp9G3X8nPF6PsY91tt1vZuBBPFo5et8ESgHd/eyWTTLKI7sRy1rtL90SOGvxvyXpx7WI5aoI9mIdioTi7oCeN/tjQeyuKQXUaeo3ylS/G5693mf65Qi3uJo3ZwKPdicAAnRJ3KpIvTQXF6Sh/5KE87UbPLG8sBj2uIXjM0giGrvk1zyOtmQ48fh8WCvqO8EsFKzEAVyZGJbeuNM31y/J5sZg7ueozhq3w/KJ+SaTTZ5nW9uUnE0duJZso20rNvsLYv0/TvsUu7npWwasU3GX79fMNEbBQaRC5suTGzWMk=
  - secure: qDN8WEXwZl+LrR6R/WMtyckxkVcQsKDA/15i0xsVRBCmjY7MHPsx9BgdYiRfbO6OFSat7MkluOxy6ZhlOzx0UVhcG77WpSi9776wjLxRLV+7eW32xYiCgzAv7YwslkARM7KFDTqL6JDP+lCIuQKdqZMuuC0WfOqxqrzu2wvJbjV8SGKxf5vfoT+KAuRsWLn8mlAPYN6BpB7xSsiHMVI5LVAzL0v7edrxjp+rUUxxZwfrbJuc9o0F9Jvabta1itlgNk3CQCau0gL4TXQvW1Bwr2b8BLXZ7vxCAAsJR/F122B37fZrGYf4Iej96rHL/rWazMwg2ToC75732G+7Y84S99Y/MkMMCo0iXP24xYMilxIYJkQxOtEMjG36HWzbq4+g5Wq8Kk6WnV5L7410HQuOV4J4tMw9PcfPzLdiSi8wJbSujFyOxclvgYynqqri2VR565nx1uFy+2cEtbmU5ehmBBNooSOkjP6Zfforzl7GmCNJivOg1JtDTb+njXRDGBksZrSI3CVlKvCWSoSHo6ntgOS4IdPNj8oV99PFqZ9ngcqNx8src4ntdB0Bpw/lV1jaBpYp7Bbt6ElRp4TpfBMCVFHegHgutUMNN81HsZlMNZw2yIPfRRIXZL3uVnucoOBRtvEOZNjonzvdiVmpQsCCoKIALETBvrl9ZkWaydjiiRQ=
  - DOCKER_IMAGE_NAME=mgufrone/ci-dredd
before_script:
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
script:
  - docker build .
after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
  - docker build -f Dockerfile -t $DOCKER_IMAGE_NAME:$COMMIT .
  - docker tag $DOCKER_IMAGE_NAME:$COMMIT $DOCKER_IMAGE_NAME:$TAG
  - docker push $DOCKER_IMAGE_NAME:$COMMIT
  - docker push $DOCKER_IMAGE_NAME:$TAG
